### ISSUE TITLE
loss adversarial.py

### ISSUE THREAD

**Issue by sheepcyyx** [MIVRC/SeaNet-PyTorch#2]
Hello, I've been reading your code recently. I have a question about the adversarial.py. According to the adversarial.py, I used --loss 1* GaN for training, which I think it is to use discriminator to judge HR and SR. But I found that the effect was poor. I would like to know if you have done a similar experiment?Looking forward to your reply！

**Comment by CV-JunchengLi** [comment]
GAN is difficult to train, how to weigh the adversarial loss is also worth studying. I have not tried using the adversarial loss to train with my model, so I cannot help you.

**Comment by sheepcyyx** [comment]
Thanks a lot！
